### ISSUE TITLE
Challenge

### ISSUE THREAD

**Issue by Tatok129** [Celeria/Skyblock-Bazaar-Status#4]
My accelerometer is garbage so I tried using the 'easter egg', but because i already did the biology question, it doesn't work, is there a way around it?

**Comment by Celeria** [comment]
Yeah, you can see in the source code unfortunately I wrote the workaround
wrong.
That's kind of my bad, I'll fix it when I get a chance....
But since you actually bothered to read the source code to find the
workaround I'll try and prioritize it a bit.

**Comment by Celeria** [comment]
But at the same time, you shouldn't have to drop your phone more than 1
Inch to trigger it, the trick is to make sure it isn't rotating....

**Comment by Celeria** [comment]
I found that holding your phone flat in one hand above your bed, with your
fingers curled slightly around it so you don't drop it for real, apply no
pressure, and just move your hand downwards quickly for a moment, and that
split moment should be enough to trigger it consistently

**Comment by Celeria** [comment]
Okay latest update actually fixed
